#ifndef SYSMON_H
#define SYSMON_H

/* Generated by cbindgen from sysmon-core/src/ffi.rs. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Starts the engine with a JSON config (`{"interval_secs":2,"mo_path":"/opt/homebrew/bin/mo",
 * "mo_version":"1.53.0","weights":{"cpu":1.0,"wakeups":0.4,"disk":0.05}}`; null means defaults).
 * Calling it again while running applies the new config in place.
 * Returns 0 started, 1 reconfigured, -1 bad config, -2 internal error.
 */
int32_t sysmon_start(const char *config_json);

/**
 * Stops the engine and terminates the Mole child. Safe to call when stopped.
 */
void sysmon_stop(void);

/**
 * Returns the latest snapshot as a JSON string, or null before the first
 * tick. Caller owns the string and must release it with `sysmon_free`.
 */
char *sysmon_snapshot_json(void);

/**
 * Releases a string returned by this library.
 */
void sysmon_free(char *ptr);

/**
 * Parses `panels.toml` text (null means the built-in defaults) into
 * `{"panels":[...],"error":null,"line":null,"default_toml":"..."}`.
 */
char *sysmon_panels_json(const char *toml_text);

#endif  /* SYSMON_H */
